---
galaxy_info:
  author: kmechlin
  description: Install Tailscale and bring up with an auth key
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - tailscale
    - networking
    - vpn
dependencies: []
