---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted

- name: Restart dcgm-exporter
  ansible.builtin.systemd:
    name: dcgm-exporter
    state: restarted
