---
- name: Roll back to a timeshift snapshot
  hosts: dgx
  become: true
  gather_facts: true
  tasks:
    - name: Include rollback tasks
      ansible.builtin.include_role:
        name: zelos.dgx.snapshot
        tasks_from: rollback.yml
