---
galaxy_info:
  author: kmechlin
  description: Install Docker CE plus NVIDIA container toolkit with nvidia default runtime
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - docker
    - nvidia
    - containers
dependencies: []
